name: Build Lighthouse

on:
  workflow_dispatch:
    inputs:
      fork_name:
        description: 'Fork of the lighthouse to clone from. If using a PR as build_target, leave it as default'
        default: 'sigp'
      build_target:
        description: 'Build target can be a tag, a branch, or a pr as "pr-ID" (e.g. pr-4126)'
        default: 'unstable'

jobs:
  build-lighthouse-binary:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, large]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install -y git gcc g++ make cmake pkg-config llvm-dev libclang-dev clang protobuf-compiler
      - name: Get latest version of stable Rust
        run: rustup update stable
      - name: Clone and run build
        run: |
          clone_url=https://github.com/${{ github.event.inputs.fork_name }}/lighthouse.git
          build_target=${{ github.event.inputs.build_target }}          
          echo "Cloning from $clone_url"
          echo "Build target: $build_target"
          git clone $clone_url && cd lighthouse && git config advice.detachedHead false && git fetch --all --tags && if [[ ${BUILD_TARGET} =~ pr-.+ ]]; then git fetch origin pull/$(echo ${BUILD_TARGET} | cut -d '-' -f 2)/head:lh-pr; git checkout lh-pr; else git checkout ${BUILD_TARGET}; fi && make        
      - name: Upload build binary
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-binary
          path: ~/.cargo/bin/lighthouse
          retention-days: 5
